### ISSUE TITLE
yum lockfile is held by another process

### ISSUE THREAD

**Issue by vmorris** [kubealex/libvirt-k8s-provisioner#11]
I often see the following failure when executing the `yum` tasks:

```
TASK [Install packages] **************************************************************************************************************************
fatal: [k8s-loadbalancer.k8s.lab]: FAILED! => {"changed": false, "msg": "yum lockfile is held by another process"}
```

This can be resolved by adding `lock_timeout` to the tasks.

**Comment by kubealex** [comment]
Thank you, can you please report me some more info? 
When does it happen, if you are doing something in the meantime, or something like that, this could help.

**Comment by vmorris** [comment]
No, nothing happening at the same time this occurs. I've added `lock_timeout` for 5 minutes to every yum task and it helps.

It's hard to duplicate, and it's a bit unfortunate that I cannot enter the ansible playbooks at any point. Instead it seems the way this is structured is that one has to run the full playbook from start to finish every time.

**Comment by kubealex** [comment]
I wasn't able to reproduce the issue in months.
Closing it
