### ISSUE TITLE
Facing issue while installing requirements and playbook

### ISSUE THREAD

**Issue by akshay-wani** [kubealex/libvirt-k8s-provisioner#76]
Hi

I tried to follow steps in repo. When I did 'ansible-galaxy collection install -r requirements.yml' it did not installed anything also not showed any error. When I tried to run 'ansible-playbook main.yml' it gives following error 

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/libvirt-k8s-provisioner/00_pre_flight_checklist.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Retrieve the minor version
      ^ here

Following is my ansible version 
root@k8s-master:~/libvirt-k8s-provisioner# ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul  1 2022, 15:56:32) [GCC 7.5.0]

Can you please help me on this? Also please provide pre-requisite doc for same if possible. 

Thanks,
Akshay

**Comment by akshay-wani** [comment]
Able to solve above issue after installing Ansible-2.9. But now facing issue at time of installing the playbook 03. It is showing error for terraform module. I've installed the requirements still it is showing error for terraform - unknown module community.general.terraform.

**Comment by voioo** [comment]
@akshay-wani install mkisofs so terraform can continue.

**Comment by kubealex** [comment]
@akshay-wani thank you for reporting it. It seems a common issue with ansible versions < 2.10 where the community.general modules were still packed in the core modules. 
Can you run a test removing the community.general prefix from the terraform module FQCN?
