### ISSUE TITLE
Great work, first time finder. 

### ISSUE THREAD

**Issue by MichaelCade** [kubealex/libvirt-k8s-provisioner#78]
Hey, Excellent work here and you have saved me a huge burden on my home lab set up. 

one small note of my onboarding is that just running 

`ansible-playbook main.yml` 

gave me some warnings and failed or just finished very quickly 

I changed a simple -i and I am now seemingly in business. 

`ansible-playbook main.yml -i inventory`

**Comment by MichaelCade** [comment]
The above was more of a recommendation. 

I am getting this error on initial run but it is getting late here so will have a look over the weekend 

`TASK [Ensure control plane VMs are in place] *********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/terraform apply -no-color -input=false -auto-approve -lock=true /tmp/tmpyxgbkedi.tfplan", "msg": "\nError: error while starting the creation of CloudInit's ISO image: exec: \"mkisofs\": executable file not found in $PATH\n\n  with libvirt_cloudinit_disk.commoninit[0],\n  on k8s-master.tf line 34, in resource \"libvirt_cloudinit_disk\" \"commoninit\":\n  34: resource \"libvirt_cloudinit_disk\" \"commoninit\" {", "rc": 1, "stderr": "\nError: error while starting the creation of CloudInit's ISO image: exec: \"mkisofs\": executable file not found in $PATH\n\n  with libvirt_cloudinit_disk.commoninit[0],\n  on k8s-master.tf line 34, in resource \"libvirt_cloudinit_disk\" \"commoninit\":\n  34: resource \"libvirt_cloudinit_disk\" \"commoninit\" {\n\n", "stderr_lines": ["", "Error: error while starting the creation of CloudInit's ISO image: exec: \"mkisofs\": executable file not found in $PATH", "", "  with libvirt_cloudinit_disk.commoninit[0],", "  on k8s-master.tf line 34, in resource \"libvirt_cloudinit_disk\" \"commoninit\":", "  34: resource \"libvirt_cloudinit_disk\" \"commoninit\" {", ""], "stdout": "libvirt_cloudinit_disk.commoninit[0]: Creating...\n", "stdout_lines": ["libvirt_cloudinit_disk.commoninit[0]: Creating..."]}`

**Comment by MichaelCade** [comment]
I tried running `mkisofs` and sure enough nothing on the host machine so I went ahead and installed using 

`sudo apt install genisoimage`

which got me past the error above. It would appear that Ubuntu 22.04 does not come with `mkisofs` installed

**Comment by kubealex** [comment]
thx a lot @MichaelCade for your input and feedback! 
If you have time and chance, would you like to contribute and add the package to the required packages for ubuntu? :) 
It'd be also great if you could report any other issue you are experiencing, if any of course!
