### ISSUE TITLE
skipping: no hosts matched

### ISSUE THREAD

**Issue by gmhafiz** [kubealex/libvirt-k8s-provisioner#83]
I may have missed a config but these are the errors I am getting after `ansible-galaxy collection install -r requirements.yml` and `ansible-playbook main.yml`

```
skipping: no hosts matched
[WARNING]: Could not match supplied host pattern, ignoring: masters
[WARNING]: Could not match supplied host pattern, ignoring: workers
```

I am, unsure where I must define `hosts` file that ansible will use, and, if this repo will provision VMs at all.

Should I create VMs before running `ansible-playbook main.yml` or I can define the hosts somewhere?

**Comment by kubealex** [comment]
Hi @gmhafiz, it seems like it is looking at the wrong place to find the inventory.
All you need is to define the VM host in the inventory (it can be localhost, or a remote host) in the provided inventory in [vm_host] group.

Then you can launch the playbook specifying the inventory:

`ansible-playbook -i inventory main.yml`

The provisioner takes care of generating a dynamic inventory for the hosts after it creates the VMs, so no effort is expected on your side.
