### ISSUE TITLE
Questions about this provisioning system

### ISSUE THREAD

**Issue by YassineElbouchaibi** [kubealex/libvirt-k8s-provisioner#88]
Hello mate, I'm looking into making use of this provisioner on my machine but before doing so I had some questions.

- If I have existing VMs configured on my host machines, could they be affected by running this provisioner ?
  - Will my existing pools, network configs, vms etc. be affected or deleted ? 
- Once an infra is first provisioned, can it be scaled (node count, resource attribution) up without loss of data?
- Could one take down the provisioned infra while persisting data for migration purposes ?

I'm sorry if any of my questions don't really make sense as I'm not very knowledgeable in this space. Thanks!

**Comment by kubealex** [comment]
Hi! I completely missed your issue @YassineElbouchaibi, my sincere apologies!
Not sure if still relevant, but:
1) No, they are not affected as long as you are not using the same values as the existing one. It will create a dedicated network, pool, and configs. 
2) Not tested, but it should be possible. 
3) Yes

Just to remark, this project is **_not_** intended for production use and comes with no support. 
I suggest using it on a clean environment to avoid any loss of data, malfunctioning or issue that is caused to your environment.
