### ISSUE TITLE
You forgot to update kubeadm-config.yaml.j2

### ISSUE THREAD

**Issue by polhaghverdian** [kubealex/libvirt-k8s-provisioner#91]
I see that you have updated to the latest patch releases for all Kubernetes major versions. However, you forgot to also change those values in kubeadm-config.yaml.j2.

`kubernetesVersion: v{{ k8s.cluster_version }}.{{ '12' if k8s.cluster_version is version('1.24', '==') else '8' if k8s.cluster_version is version('1.25', '==') else '3' if k8s.cluster_version is version('1.26', '==') else '0' if k8s.cluster_version is version('1.27', '==') }}`

**Comment by kubealex** [comment]
Thank you @polhaghverdian, ops! Fixed and pushed!
