### ISSUE TITLE
Any idea why this is happening sometimes?

### ISSUE THREAD

**Issue by polhaghverdian** [kubealex/libvirt-k8s-provisioner#93]
```
TASK [Join control-plane nodes in cluster] ******************************************************************************************************************************************************************************************
fatal: [k8s-venom-master-1.k8s.lab]: FAILED! => {"changed": true, "cmd": ["kubeadm", "join", "--config", "/tmp/kubeadm-join.yaml"], "delta": "0:00:53.646320", "end": "2023-09-25 12:24:52.184083", "msg": "non-zero return code", "rc": 1, "start": "2023-09-25 12:23:58.537763", "stderr": "W0925 12:24:18.215730    2942 checks.go:835] detected that the sandbox image \"registry.k8s.io/pause:3.6\" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using \"registry.k8s.io/pause:3.9\" as the CRI sandbox image.\nerror execution phase control-plane-prepare/download-certs: error downloading certs: error downloading the secret: Get \"https://k8s-venom-loadbalancer.k8s.lab:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["W0925 12:24:18.215730    2942 checks.go:835] detected that the sandbox image \"registry.k8s.io/pause:3.6\" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using \"registry.k8s.io/pause:3.9\" as the CRI sandbox image.", "error execution phase control-plane-prepare/download-certs: error downloading certs: error downloading the secret: Get \"https://k8s-venom-loadbalancer.k8s.lab:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[preflight] Running pre-flight checks\n[preflight] Reading configuration from the cluster...\n[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'\n[preflight] Running pre-flight checks before initializing the new control plane instance\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\n[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace", "stdout_lines": ["[preflight] Running pre-flight checks", "[preflight] Reading configuration from the cluster...", "[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'", "[preflight] Running pre-flight checks before initializing the new control plane instance", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace"]}

I think the interesting part is this: 
`detected that the sandbox image \"registry.k8s.io/pause:3.6\" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using \"registry.k8s.io/pause:3.9\" as the CRI sandbox image.", `

```

**Comment by kubealex** [comment]
hi @polhaghverdian! 
Thank you for reporting this. 
The mentioned line is a warning related to CRI-O defaults if I am not mistaken and it should not be linked in any way to the error (it would happen every time, instead of sometimes).

When the issue happens, if you try to replicate the REST call to [](https://k8s-venom-loadbalancer.k8s.lab:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s\) do you get any insights?

I suspect it could be that the loadbalancer or any of the enpoints (i.e. master nodes) are up and running but the API server could be unable to satisfy the request at that time, closing the connection.

Is there any other symptom that could help addressing this scenario?

Thank you!

**Comment by polhaghverdian** [comment]
Hi, @kubealex  I will try to replicate the REST call when I stumble upon the issue again. Didn't know you would answer this quickly, otherwise, I would have waited and not re-run the playbook. The issue is not very critical, but it can be annoying from time to time.

**Comment by polhaghverdian** [comment]
Ok. After re-running the playbook a couple of times, I now get below error: 

`fatal: [k8s-venom-master-2.k8s.lab]: FAILED! => {"changed": true, "cmd": ["kubeadm", "join", "--config", "/tmp/kubeadm-join.yaml"], "delta": "0:00:53.729230", "end": "2023-09-25 17:21:06.385309", "msg": "non-zero return code", "rc": 1, "start": "2023-09-25 17:20:12.656079", "stderr": "W0925 17:20:43.068669    2935 checks.go:835] detected that the sandbox image \"registry.k8s.io/pause:3.6\" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using \"registry.k8s.io/pause:3.9\" as the CRI sandbox image.\nerror execution phase control-plane-prepare/download-certs: error downloading certs: error downloading the secret: etcdserver: leader changed\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["W0925 17:20:43.068669    2935 checks.go:835] detected that the sandbox image \"registry.k8s.io/pause:3.6\" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using \"registry.k8s.io/pause:3.9\" as the CRI sandbox image.", "error execution phase control-plane-prepare/download-certs: error downloading certs: error downloading the secret: etcdserver: leader changed", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "[preflight] Running pre-flight checks\n[preflight] Reading configuration from the cluster...\n[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'\n[preflight] Running pre-flight checks before initializing the new control plane instance\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\n[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace", "stdout_lines": ["[preflight] Running pre-flight checks", "[preflight] Reading configuration from the cluster...", "[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'", "[preflight] Running pre-flight checks before initializing the new control plane instance", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "[download-certs] Downloading the certificates in Secret \"kubeadm-certs\" in the \"kube-system\" Namespace"]}`

**Comment by polhaghverdian** [comment]
```
$ wget https://k8s-venom-loadbalancer.k8s.lab:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s --no-check-certificate
--2023-09-25 19:34:42--  https://k8s-venom-loadbalancer.k8s.lab:6443/api/v1/namespaces/kube-system/secrets/kubeadm-certs?timeout=10s
Resolving k8s-venom-loadbalancer.k8s.lab (k8s-venom-loadbalancer.k8s.lab)... 192.168.2.193
Connecting to k8s-venom-loadbalancer.k8s.lab (k8s-venom-loadbalancer.k8s.lab)|192.168.2.193|:6443... connected.
WARNING: cannot verify k8s-venom-loadbalancer.k8s.lab's certificate, issued by ‘CN=kubernetes’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-25 19:34:42 ERROR 403: Forbidden.
```

**Comment by polhaghverdian** [comment]
I am closing this issue.  Because following solution worked, by adding **--skip-phases=preflight**,  the issue has been gone for two weeks and which I have been constantly destroying and creating new clusters without any issues.
```

         - name: Join control-plane nodes in cluster
          ansible.builtin.command: kubeadm join --skip-phases=preflight --config /tmp/kubeadm-join.yaml
          become: true
```
